version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/mimir"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/mimir/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_mimir"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_mimir/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/mimir/native"
    schedule:
      interval: weekly