name: mimir

repository: https://github.com/GregoryConrad/mimir

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**

scripts:
  analyze:
    exec: flutter analyze .

  # TODO build apple

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec --fail-fast -- "dart test test"
    description: Run Dart tests for a specific package in this project.
    select-package:
      flutter: false
      dir-exists: test

  test:flutter:
    run: melos exec --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
