[package]
name = "embedded_milli"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.53.*"

[dependencies]
flutter_rust_bridge = "1.54.*"
anyhow = "1.0.*"
serde = "1.0.*"
serde_json = "1.0.*"
parking_lot = "0.12.*"
lazy_static = "1.*"
# milli_v1 = { git = "https://github.com/meilisearch/milli", tag = "v0.38.0", package = "milli" }
milli_v1 = { git = "https://github.com/GregoryConrad/milli", branch="filter-parser-convenience", package = "milli" }
