[package]
name = "embedded_milli"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "=1.72.2"

[dependencies]
flutter_rust_bridge = "=1.72.1"
anyhow = "1.0.*"
serde = "1.0.*"
serde_json = "1.0.*"
parking_lot = "0.12.*"
lazy_static = "1.*"
milli_v1 = { git = "https://github.com/meilisearch/meilisearch", package = "milli", branch = "main" }

[features]
# POSIX semaphores are needed for Apple's App Sandbox.
# Default LMDB uses SysV semaphores but App Sandbox disallows them.
# See https://github.com/GregoryConrad/mimir/issues/98
posix-sem = ["milli_v1/lmdb-posix-sem",]
