name: flutter_mimir_example
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # You can replace these with the latest versions
  flutter_mimir: ^0.0.2-dev.1
  mimir: ^0.0.2-dev.1

  # These two are used in the example; they are not required by mimir
  rearch: ^0.0.0-dev.3
  flutter_rearch: ^0.0.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # Copied from https://github.com/glin/reactable/blob/d8310ca34e1055d490c0a6b5af5fa0c7f291a709/vignettes/popular-movies/tmdb_movies.json
    - assets/tmdb_movies.json
