name: flutter_mimir_example
description: flutter_mimir example application
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0-339.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # You can replace these with the latest versions
  flutter_mimir: ^0.0.1-dev.8
  mimir: ^0.0.1-dev.8

  # These two are used in the example; they are not required by mimir
  unstate: ^1.0.0
  flutter_unstate: ^1.0.0

dependency_overrides:
  unstate:
    path: ../../../../unstate/packages/unstate
  flutter_unstate:
    path: ../../../../unstate/packages/flutter_unstate

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # Copied from https://github.com/glin/reactable/blob/d8310ca34e1055d490c0a6b5af5fa0c7f291a709/vignettes/popular-movies/tmdb_movies.json
    - assets/tmdb_movies.json
