name: mimir
description: >
  Extremely powerful, reactive database with
  typo-tolerant full-text search and declarative queries.
version: 0.0.1-dev.1
homepage: https://github.com/GregoryConrad/mimir
repository: https://github.com/GregoryConrad/mimir

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: "1.61.1"
  freezed_annotation: ^2.2.0
  meta: ^1.8.0

dev_dependencies:
  analyzer: ^5.2.0
  build_runner: ^2.3.2
  ffigen: ^7.2.0
  freezed: ^2.2.1
  test: ^1.22.0
