name: flutter_mimir
description: >
  Extremely powerful, reactive database with
  typo-tolerant full-text search and declarative queries.
version: 0.0.0-dev.4
homepage: https://github.com/GregoryConrad/mimir
repository: https://github.com/GregoryConrad/mimir

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mimir: ^0.0.0-dev.4
  path: ^1.8.2
  path_provider: ^2.0.11

dev_dependencies:
  analyzer: ^5.2.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
