name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  # General build, check, and test steps
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # General setup
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: subosito/flutter-action@v2

      # Melos setup
      - name: Install Melos
        run: |
          dart pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Bootstrap Melos
        run: melos bs

      # Rust checks
      - name: Build Rust code (embedded_milli)
        working-directory: ./packages/mimir/native
        run: cargo build

      # Dart/Flutter checks
      - name: Check format
        run: melos run check-format --no-select

      - name: Analyze
        run: melos run analyze --no-select

      - name: Run tests
        run: melos run test

  # TODO For integration tests, maybe see:
  # https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/.github/workflows/flutter_ios_test.yml

  # TODO Flutter desktop integration tests
  desktop_integration_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        flutter_channel: [stable]
        package_path:
          - packages/flutter_mimir
          - packages/flutter_mimir/example

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ${{ matrix.package_path }}

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter_channel }}

      - name: Install current package dependencies
        run: flutter pub get


  # TODO Flutter iOS integration tests
  ios_integration_tests:
    strategy:
      matrix:
        os: [macos-latest]
        flutter_channel: [stable]
        package_path:
          - packages/flutter_mimir
          - packages/flutter_mimir/example

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ${{ matrix.package_path }}

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter_channel }}

      - name: Install current package dependencies
        run: flutter pub get


  # TODO Flutter Android integration tests
  android_integration_tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        flutter_channel: [stable]
        package_path:
          - packages/flutter_mimir
          - packages/flutter_mimir/example

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ${{ matrix.package_path }}

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter_channel }}

      - name: Install current package dependencies
        run: flutter pub get
