name: Publish Release(s)

on:
  push:
    tags:
      - '*'

jobs:
  publish_release:
    # macOS because we can cross-compile to all other platforms from it
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e # TODO try latest version?

      - name: Build all library binaries
        run: melos run build

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: packages/mimir/native/build/*

      - name: Setup pub.dev credentials
        run: |
          mkdir -p "~/Library/Application Support/dart/"
          cat << EOF > "~/Library/Application Support/dart/pub-credentials.json"
          ${{ secrets.PUB_CRED_JSON }}
          EOF
      - name: Dry-run publish to pub.dev
        run: melos publish -y --dry-run
      - name: Publish to pub.dev
        run: melos publish -y --no-dry-run
